// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentStatus string

const (
	DeploymentStatusPending     DeploymentStatus = "pending"
	DeploymentStatusDeploying   DeploymentStatus = "deploying"
	DeploymentStatusActive      DeploymentStatus = "active"
	DeploymentStatusCanary      DeploymentStatus = "canary"
	DeploymentStatusRollingBack DeploymentStatus = "rolling_back"
	DeploymentStatusFailed      DeploymentStatus = "failed"
	DeploymentStatusInactive    DeploymentStatus = "inactive"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type RuleType string

const (
	RuleTypeList RuleType = "list"
	RuleTypeFlow RuleType = "flow"
)

func (e *RuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleType(s)
	case string:
		*e = RuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleType: %T", src)
	}
	return nil
}

type NullRuleType struct {
	RuleType RuleType `json:"rule_type"`
	Valid    bool     `json:"valid"` // Valid is true if RuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.RuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleType), nil
}

type RulesetStatus string

const (
	RulesetStatusDraft      RulesetStatus = "draft"
	RulesetStatusValidating RulesetStatus = "validating"
	RulesetStatusReady      RulesetStatus = "ready"
	RulesetStatusDeployed   RulesetStatus = "deployed"
	RulesetStatusDeprecated RulesetStatus = "deprecated"
	RulesetStatusFailed     RulesetStatus = "failed"
)

func (e *RulesetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RulesetStatus(s)
	case string:
		*e = RulesetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RulesetStatus: %T", src)
	}
	return nil
}

type NullRulesetStatus struct {
	RulesetStatus RulesetStatus `json:"ruleset_status"`
	Valid         bool          `json:"valid"` // Valid is true if RulesetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRulesetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RulesetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RulesetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRulesetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RulesetStatus), nil
}

type AuditLog struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Action         string             `db:"action" json:"action"`
	Resource       string             `db:"resource" json:"resource"`
	ResourceID     uuid.UUID          `db:"resource_id" json:"resource_id"`
	Version        pgtype.Text        `db:"version" json:"version"`
	Environment    pgtype.Text        `db:"environment" json:"environment"`
	UserID         pgtype.Text        `db:"user_id" json:"user_id"`
	UserEmail      pgtype.Text        `db:"user_email" json:"user_email"`
	IpAddress      net.IP             `db:"ip_address" json:"ip_address"`
	UserAgent      pgtype.Text        `db:"user_agent" json:"user_agent"`
	SessionID      pgtype.Text        `db:"session_id" json:"session_id"`
	Details        json.RawMessage    `db:"details" json:"details"`
	RequestID      pgtype.Text        `db:"request_id" json:"request_id"`
	TraceID        pgtype.Text        `db:"trace_id" json:"trace_id"`
	Result         string             `db:"result" json:"result"`
	ErrorMessage   pgtype.Text        `db:"error_message" json:"error_message"`
	DurationMs     pgtype.Int4        `db:"duration_ms" json:"duration_ms"`
	Timestamp      pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	MonthPartition pgtype.Int4        `db:"month_partition" json:"month_partition"`
}

type Deployment struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Environment struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	Name                string             `db:"name" json:"name"`
	Type                string             `db:"type" json:"type"`
	Config              json.RawMessage    `db:"config" json:"config"`
	Constraints         json.RawMessage    `db:"constraints" json:"constraints"`
	Approvers           []string           `db:"approvers" json:"approvers"`
	AutoDeploy          pgtype.Bool        `db:"auto_deploy" json:"auto_deploy"`
	RequireApproval     pgtype.Bool        `db:"require_approval" json:"require_approval"`
	MaxRuleComplexity   pgtype.Int4        `db:"max_rule_complexity" json:"max_rule_complexity"`
	PerformanceBudgetMs pgtype.Int4        `db:"performance_budget_ms" json:"performance_budget_ms"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RuleMetric struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	RulesetID       uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	ExecutionCount  pgtype.Int8        `db:"execution_count" json:"execution_count"`
	SuccessCount    pgtype.Int8        `db:"success_count" json:"success_count"`
	ErrorCount      pgtype.Int8        `db:"error_count" json:"error_count"`
	TotalDurationMs pgtype.Int8        `db:"total_duration_ms" json:"total_duration_ms"`
	MinDurationMs   pgtype.Int4        `db:"min_duration_ms" json:"min_duration_ms"`
	MaxDurationMs   pgtype.Int4        `db:"max_duration_ms" json:"max_duration_ms"`
	AvgDurationMs   pgtype.Int4        `db:"avg_duration_ms" json:"avg_duration_ms"`
	MemoryUsageMb   pgtype.Int4        `db:"memory_usage_mb" json:"memory_usage_mb"`
	CpuUsagePercent pgtype.Numeric     `db:"cpu_usage_percent" json:"cpu_usage_percent"`
	LastExecutedAt  pgtype.Timestamptz `db:"last_executed_at" json:"last_executed_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Ruleset struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Version         string             `db:"version" json:"version"`
	Environment     string             `db:"environment" json:"environment"`
	Status          RulesetStatus      `db:"status" json:"status"`
	RulesetData     json.RawMessage    `db:"ruleset_data" json:"ruleset_data"`
	RuleCount       int32              `db:"rule_count" json:"rule_count"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Tags            []string           `db:"tags" json:"tags"`
	Owner           pgtype.Text        `db:"owner" json:"owner"`
	Team            pgtype.Text        `db:"team" json:"team"`
	Metadata        json.RawMessage    `db:"metadata" json:"metadata"`
	GitCommit       pgtype.Text        `db:"git_commit" json:"git_commit"`
	GitBranch       pgtype.Text        `db:"git_branch" json:"git_branch"`
	GitTag          pgtype.Text        `db:"git_tag" json:"git_tag"`
	GitAuthor       pgtype.Text        `db:"git_author" json:"git_author"`
	PullRequest     pgtype.Text        `db:"pull_request" json:"pull_request"`
	CompiledAt      pgtype.Timestamptz `db:"compiled_at" json:"compiled_at"`
	CompilerVersion pgtype.Text        `db:"compiler_version" json:"compiler_version"`
	SchemaVersion   pgtype.Text        `db:"schema_version" json:"schema_version"`
	ValidationHash  pgtype.Text        `db:"validation_hash" json:"validation_hash"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy       pgtype.Text        `db:"created_by" json:"created_by"`
	UpdatedBy       pgtype.Text        `db:"updated_by" json:"updated_by"`
}
