CREATE TABLE IF NOT EXISTS scrape_orders (
  event_id BIGSERIAL PRIMARY KEY,
  order_id TEXT NOT NULL,
  amount NUMERIC,
  currency TEXT,
  state TEXT,
  created_at_epoch BIGINT,
  priority TEXT,
  sku TEXT,
  customer_id TEXT,
  customer_risk_score INT,
  customer_priority INT,
  payment_auth_id TEXT,
  payment_state TEXT,
  inventory_available BOOLEAN,
  device_id TEXT,
  risk_stream_score INT,
  chargeback_open BOOLEAN,
  updated_at_epoch BIGINT
);

INSERT INTO scrape_orders (
  order_id,
  amount,
  currency,
  state,
  created_at_epoch,
  priority,
  sku,
  customer_id,
  customer_risk_score,
  customer_priority,
  payment_auth_id,
  payment_state,
  inventory_available,
  device_id,
  risk_stream_score,
  chargeback_open,
  updated_at_epoch
) VALUES (
  'ord-9001',
  2450.75,
  'USD',
  'pending',
  1735270000,
  'expedite',
  'sku-rocket',
  'cust-77',
  82,
  2,
  'auth-abc-123',
  'authorized',
  true,
  'dev-44',
  88,
  false,
  1735274000
);
