apiVersion: v1
kind: Service
metadata:
  name: {{ include "effectusd.fullname" . }}
  labels:
    {{- include "effectusd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.grpc.enabled }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: grpc
      appProtocol: grpc
    {{- end }}
  selector:
    {{- include "effectusd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
