// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deployments.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CompleteDeployment = `-- name: CompleteDeployment :one
UPDATE deployments 
SET 
    status = 'active',
    completed_at = CURRENT_TIMESTAMP,
    deployment_duration_ms = EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - deployed_at))::INTEGER * 1000,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at
`

func (q *Queries) CompleteDeployment(ctx context.Context, id uuid.UUID) (*Deployment, error) {
	row := q.db.QueryRow(ctx, CompleteDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const CreateDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (
    ruleset_id, environment, status, strategy,
    config, health_check, rollback_info, canary_config,
    deployed_by, deployment_duration_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at
`

// Deployment queries for sqlc code generation
func (q *Queries) CreateDeployment(ctx context.Context, rulesetID uuid.UUID, environment string, status DeploymentStatus, strategy string, config json.RawMessage, healthCheck json.RawMessage, rollbackInfo json.RawMessage, canaryConfig json.RawMessage, deployedBy pgtype.Text, deploymentDurationMs pgtype.Int4) (*Deployment, error) {
	row := q.db.QueryRow(ctx, CreateDeployment,
		rulesetID,
		environment,
		status,
		strategy,
		config,
		healthCheck,
		rollbackInfo,
		canaryConfig,
		deployedBy,
		deploymentDurationMs,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeactivateOldDeployments = `-- name: DeactivateOldDeployments :exec
UPDATE deployments 
SET 
    status = 'inactive',
    updated_at = CURRENT_TIMESTAMP
WHERE environment = $1 AND status = 'active' AND id != $2
`

func (q *Queries) DeactivateOldDeployments(ctx context.Context, environment string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeactivateOldDeployments, environment, iD)
	return err
}

const GetActiveDeployment = `-- name: GetActiveDeployment :one
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE d.environment = $1 AND d.status = 'active'
ORDER BY d.deployed_at DESC
LIMIT 1
`

type GetActiveDeploymentRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetActiveDeployment(ctx context.Context, environment string) (*GetActiveDeploymentRow, error) {
	row := q.db.QueryRow(ctx, GetActiveDeployment, environment)
	var i GetActiveDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RulesetName,
		&i.RulesetVersion,
	)
	return &i, err
}

const GetCanaryDeployments = `-- name: GetCanaryDeployments :many
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE d.status = 'canary'
ORDER BY d.deployed_at DESC
`

type GetCanaryDeploymentsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetCanaryDeployments(ctx context.Context) ([]*GetCanaryDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, GetCanaryDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCanaryDeploymentsRow{}
	for rows.Next() {
		var i GetCanaryDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDeployment = `-- name: GetDeployment :one
SELECT id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at FROM deployments 
WHERE ruleset_id = $1 AND environment = $2
`

func (q *Queries) GetDeployment(ctx context.Context, rulesetID uuid.UUID, environment string) (*Deployment, error) {
	row := q.db.QueryRow(ctx, GetDeployment, rulesetID, environment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at FROM deployments 
WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (*Deployment, error) {
	row := q.db.QueryRow(ctx, GetDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetDeploymentHistory = `-- name: GetDeploymentHistory :many
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE d.environment = $1
ORDER BY d.deployed_at DESC
LIMIT $2
`

type GetDeploymentHistoryRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetDeploymentHistory(ctx context.Context, environment string, limit int32) ([]*GetDeploymentHistoryRow, error) {
	rows, err := q.db.Query(ctx, GetDeploymentHistory, environment, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDeploymentHistoryRow{}
	for rows.Next() {
		var i GetDeploymentHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDeploymentStats = `-- name: GetDeploymentStats :one
SELECT 
    COUNT(*) as total_deployments,
    COUNT(*) FILTER (WHERE status = 'active') as active_deployments,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_deployments,
    COUNT(*) FILTER (WHERE status = 'canary') as canary_deployments,
    AVG(deployment_duration_ms) FILTER (WHERE deployment_duration_ms IS NOT NULL) as avg_deployment_duration_ms,
    COUNT(DISTINCT environment) as total_environments
FROM deployments
WHERE deployed_at >= $1
`

type GetDeploymentStatsRow struct {
	TotalDeployments        int64   `db:"total_deployments" json:"total_deployments"`
	ActiveDeployments       int64   `db:"active_deployments" json:"active_deployments"`
	FailedDeployments       int64   `db:"failed_deployments" json:"failed_deployments"`
	CanaryDeployments       int64   `db:"canary_deployments" json:"canary_deployments"`
	AvgDeploymentDurationMs float64 `db:"avg_deployment_duration_ms" json:"avg_deployment_duration_ms"`
	TotalEnvironments       int64   `db:"total_environments" json:"total_environments"`
}

func (q *Queries) GetDeploymentStats(ctx context.Context, deployedAt pgtype.Timestamptz) (*GetDeploymentStatsRow, error) {
	row := q.db.QueryRow(ctx, GetDeploymentStats, deployedAt)
	var i GetDeploymentStatsRow
	err := row.Scan(
		&i.TotalDeployments,
		&i.ActiveDeployments,
		&i.FailedDeployments,
		&i.CanaryDeployments,
		&i.AvgDeploymentDurationMs,
		&i.TotalEnvironments,
	)
	return &i, err
}

const GetDeploymentsByRuleset = `-- name: GetDeploymentsByRuleset :many
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE r.name = $1
ORDER BY d.deployed_at DESC
LIMIT $2
`

type GetDeploymentsByRulesetRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetDeploymentsByRuleset(ctx context.Context, name string, limit int32) ([]*GetDeploymentsByRulesetRow, error) {
	rows, err := q.db.Query(ctx, GetDeploymentsByRuleset, name, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDeploymentsByRulesetRow{}
	for rows.Next() {
		var i GetDeploymentsByRulesetRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEnvironmentDeployments = `-- name: GetEnvironmentDeployments :many
SELECT DISTINCT ON (r.name) 
    d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE d.environment = $1 AND d.status = 'active'
ORDER BY r.name, d.deployed_at DESC
`

type GetEnvironmentDeploymentsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetEnvironmentDeployments(ctx context.Context, environment string) ([]*GetEnvironmentDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, GetEnvironmentDeployments, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEnvironmentDeploymentsRow{}
	for rows.Next() {
		var i GetEnvironmentDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFailedDeployments = `-- name: GetFailedDeployments :many
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE d.status = 'failed' AND d.deployed_at >= $1
ORDER BY d.deployed_at DESC
LIMIT $2
`

type GetFailedDeploymentsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) GetFailedDeployments(ctx context.Context, deployedAt pgtype.Timestamptz, limit int32) ([]*GetFailedDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, GetFailedDeployments, deployedAt, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFailedDeploymentsRow{}
	for rows.Next() {
		var i GetFailedDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDeployments = `-- name: ListDeployments :many
SELECT d.id, d.ruleset_id, d.environment, d.status, d.strategy, d.config, d.health_check, d.rollback_info, d.canary_config, d.deployed_at, d.completed_at, d.deployed_by, d.deployment_duration_ms, d.created_at, d.updated_at, r.name as ruleset_name, r.version as ruleset_version
FROM deployments d
JOIN rulesets r ON d.ruleset_id = r.id
WHERE 
    ($1::text IS NULL OR d.environment = $1)
    AND ($2::deployment_status[] IS NULL OR d.status = ANY($2::deployment_status[]))
    AND ($3::text IS NULL OR d.deployed_by = $3)
    AND ($4::timestamptz IS NULL OR d.deployed_at >= $4)
    AND ($5::timestamptz IS NULL OR d.deployed_at <= $5)
ORDER BY d.deployed_at DESC
LIMIT $6
`

type ListDeploymentsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	RulesetID            uuid.UUID          `db:"ruleset_id" json:"ruleset_id"`
	Environment          string             `db:"environment" json:"environment"`
	Status               DeploymentStatus   `db:"status" json:"status"`
	Strategy             string             `db:"strategy" json:"strategy"`
	Config               json.RawMessage    `db:"config" json:"config"`
	HealthCheck          json.RawMessage    `db:"health_check" json:"health_check"`
	RollbackInfo         json.RawMessage    `db:"rollback_info" json:"rollback_info"`
	CanaryConfig         json.RawMessage    `db:"canary_config" json:"canary_config"`
	DeployedAt           pgtype.Timestamptz `db:"deployed_at" json:"deployed_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeployedBy           pgtype.Text        `db:"deployed_by" json:"deployed_by"`
	DeploymentDurationMs pgtype.Int4        `db:"deployment_duration_ms" json:"deployment_duration_ms"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RulesetName          string             `db:"ruleset_name" json:"ruleset_name"`
	RulesetVersion       string             `db:"ruleset_version" json:"ruleset_version"`
}

func (q *Queries) ListDeployments(ctx context.Context, column1 string, column2 []DeploymentStatus, column3 string, column4 pgtype.Timestamptz, column5 pgtype.Timestamptz, limit int32) ([]*ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, ListDeployments,
		column1,
		column2,
		column3,
		column4,
		column5,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListDeploymentsRow{}
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Environment,
			&i.Status,
			&i.Strategy,
			&i.Config,
			&i.HealthCheck,
			&i.RollbackInfo,
			&i.CanaryConfig,
			&i.DeployedAt,
			&i.CompletedAt,
			&i.DeployedBy,
			&i.DeploymentDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesetName,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetDeploymentRollback = `-- name: SetDeploymentRollback :one
UPDATE deployments 
SET 
    status = 'rolling_back',
    rollback_info = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at
`

func (q *Queries) SetDeploymentRollback(ctx context.Context, iD uuid.UUID, rollbackInfo json.RawMessage) (*Deployment, error) {
	row := q.db.QueryRow(ctx, SetDeploymentRollback, iD, rollbackInfo)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateDeploymentHealthCheck = `-- name: UpdateDeploymentHealthCheck :one
UPDATE deployments 
SET 
    health_check = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at
`

func (q *Queries) UpdateDeploymentHealthCheck(ctx context.Context, iD uuid.UUID, healthCheck json.RawMessage) (*Deployment, error) {
	row := q.db.QueryRow(ctx, UpdateDeploymentHealthCheck, iD, healthCheck)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments 
SET 
    status = $2,
    completed_at = CASE WHEN $2 IN ('active', 'failed', 'inactive') THEN CURRENT_TIMESTAMP ELSE completed_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, ruleset_id, environment, status, strategy, config, health_check, rollback_info, canary_config, deployed_at, completed_at, deployed_by, deployment_duration_ms, created_at, updated_at
`

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, iD uuid.UUID, status DeploymentStatus) (*Deployment, error) {
	row := q.db.QueryRow(ctx, UpdateDeploymentStatus, iD, status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.RulesetID,
		&i.Environment,
		&i.Status,
		&i.Strategy,
		&i.Config,
		&i.HealthCheck,
		&i.RollbackInfo,
		&i.CanaryConfig,
		&i.DeployedAt,
		&i.CompletedAt,
		&i.DeployedBy,
		&i.DeploymentDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
