// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"encoding/json"
	"net"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupOldAuditLogs(ctx context.Context, timestamp pgtype.Timestamptz) error
	CompleteDeployment(ctx context.Context, id uuid.UUID) (*Deployment, error)
	CountRulesetsByStatus(ctx context.Context, environment string) ([]*CountRulesetsByStatusRow, error)
	// Audit log queries for sqlc code generation
	CreateAuditEntry(ctx context.Context, action string, resource string, resourceID uuid.UUID, version pgtype.Text, environment pgtype.Text, userID pgtype.Text, userEmail pgtype.Text, ipAddress net.IP, userAgent pgtype.Text, sessionID pgtype.Text, details json.RawMessage, requestID pgtype.Text, traceID pgtype.Text, result string, errorMessage pgtype.Text, durationMs pgtype.Int4) (*AuditLog, error)
	// Deployment queries for sqlc code generation
	CreateDeployment(ctx context.Context, rulesetID uuid.UUID, environment string, status DeploymentStatus, strategy string, config json.RawMessage, healthCheck json.RawMessage, rollbackInfo json.RawMessage, canaryConfig json.RawMessage, deployedBy pgtype.Text, deploymentDurationMs pgtype.Int4) (*Deployment, error)
	// Ruleset queries for sqlc code generation
	CreateRuleset(ctx context.Context, name string, version string, environment string, status RulesetStatus, rulesetData json.RawMessage, ruleCount int32, description pgtype.Text, tags []string, owner pgtype.Text, team pgtype.Text, metadata json.RawMessage, gitCommit pgtype.Text, gitBranch pgtype.Text, gitTag pgtype.Text, gitAuthor pgtype.Text, pullRequest pgtype.Text, compiledAt pgtype.Timestamptz, compilerVersion pgtype.Text, schemaVersion pgtype.Text, validationHash pgtype.Text, createdBy pgtype.Text, updatedBy pgtype.Text) (*Ruleset, error)
	DeactivateOldDeployments(ctx context.Context, environment string, iD uuid.UUID) error
	DeleteRuleset(ctx context.Context, id uuid.UUID) error
	GetActiveDeployment(ctx context.Context, environment string) (*GetActiveDeploymentRow, error)
	GetAuditLogs(ctx context.Context, column1 []string, column2 []string, column3 []string, column4 pgtype.Timestamptz, column5 pgtype.Timestamptz, column6 string, column7 string, limit int32, offset int32) ([]*AuditLog, error)
	GetAuditLogsByResource(ctx context.Context, resource string, column2 string, limit int32) ([]*AuditLog, error)
	GetAuditLogsBySession(ctx context.Context, sessionID pgtype.Text) ([]*AuditLog, error)
	GetAuditLogsByTrace(ctx context.Context, traceID pgtype.Text) ([]*AuditLog, error)
	GetAuditLogsByUser(ctx context.Context, userID pgtype.Text, timestamp pgtype.Timestamptz, limit int32) ([]*AuditLog, error)
	GetAuditStats(ctx context.Context, timestamp pgtype.Timestamptz) (*GetAuditStatsRow, error)
	GetCanaryDeployments(ctx context.Context) ([]*GetCanaryDeploymentsRow, error)
	GetDeployment(ctx context.Context, rulesetID uuid.UUID, environment string) (*Deployment, error)
	GetDeploymentByID(ctx context.Context, id uuid.UUID) (*Deployment, error)
	GetDeploymentHistory(ctx context.Context, environment string, limit int32) ([]*GetDeploymentHistoryRow, error)
	GetDeploymentStats(ctx context.Context, deployedAt pgtype.Timestamptz) (*GetDeploymentStatsRow, error)
	GetDeploymentsByRuleset(ctx context.Context, name string, limit int32) ([]*GetDeploymentsByRulesetRow, error)
	GetEnvironmentDeployments(ctx context.Context, environment string) ([]*GetEnvironmentDeploymentsRow, error)
	GetFailedDeployments(ctx context.Context, deployedAt pgtype.Timestamptz, limit int32) ([]*GetFailedDeploymentsRow, error)
	GetFailedOperations(ctx context.Context, timestamp pgtype.Timestamptz, limit int32) ([]*AuditLog, error)
	GetLatestRuleset(ctx context.Context, name string, environment string) (*Ruleset, error)
	GetRecentErrorsCount(ctx context.Context, timestamp pgtype.Timestamptz) (int64, error)
	GetRecentRulesets(ctx context.Context, createdAt pgtype.Timestamptz, limit int32) ([]*Ruleset, error)
	GetRuleset(ctx context.Context, name string, version string, environment string) (*Ruleset, error)
	GetRulesetByID(ctx context.Context, id uuid.UUID) (*Ruleset, error)
	GetRulesetStats(ctx context.Context) (*GetRulesetStatsRow, error)
	GetRulesetVersions(ctx context.Context, name string, environment string) ([]*GetRulesetVersionsRow, error)
	GetRulesetsByGitCommit(ctx context.Context, gitCommit pgtype.Text) ([]*Ruleset, error)
	GetRulesetsByTags(ctx context.Context, column1 []string, environment string, limit int32) ([]*Ruleset, error)
	GetRulesetsByTeam(ctx context.Context, team pgtype.Text, environment string, limit int32) ([]*Ruleset, error)
	GetSecurityEvents(ctx context.Context, timestamp pgtype.Timestamptz, limit int32) ([]*AuditLog, error)
	GetTopActions(ctx context.Context, timestamp pgtype.Timestamptz, limit int32) ([]*GetTopActionsRow, error)
	GetTopUsers(ctx context.Context, timestamp pgtype.Timestamptz, limit int32) ([]*GetTopUsersRow, error)
	ListDeployments(ctx context.Context, column1 string, column2 []DeploymentStatus, column3 string, column4 pgtype.Timestamptz, column5 pgtype.Timestamptz, limit int32) ([]*ListDeploymentsRow, error)
	ListRulesets(ctx context.Context, column1 string, column2 []string, column3 []RulesetStatus, column4 string, column5 string, column6 []string, column7 pgtype.Timestamptz, column8 string, column9 string, limit int32) ([]*ListRulesetsRow, error)
	SearchAuditLogs(ctx context.Context, plaintoTsquery string, timestamp pgtype.Timestamptz, limit int32) ([]*AuditLog, error)
	SearchRulesets(ctx context.Context, plaintoTsquery string, limit int32) ([]*SearchRulesetsRow, error)
	SetDeploymentRollback(ctx context.Context, iD uuid.UUID, rollbackInfo json.RawMessage) (*Deployment, error)
	UpdateDeploymentHealthCheck(ctx context.Context, iD uuid.UUID, healthCheck json.RawMessage) (*Deployment, error)
	UpdateDeploymentStatus(ctx context.Context, iD uuid.UUID, status DeploymentStatus) (*Deployment, error)
	UpdateRuleset(ctx context.Context, iD uuid.UUID, status RulesetStatus, rulesetData json.RawMessage, ruleCount int32, description pgtype.Text, tags []string, metadata json.RawMessage, updatedBy pgtype.Text) (*Ruleset, error)
	UpdateRulesetStatus(ctx context.Context, iD uuid.UUID, status RulesetStatus, updatedBy pgtype.Text) (*Ruleset, error)
	UpsertRuleset(ctx context.Context, name string, version string, environment string, status RulesetStatus, rulesetData json.RawMessage, ruleCount int32, description pgtype.Text, tags []string, owner pgtype.Text, team pgtype.Text, metadata json.RawMessage, gitCommit pgtype.Text, gitBranch pgtype.Text, gitTag pgtype.Text, gitAuthor pgtype.Text, pullRequest pgtype.Text, compiledAt pgtype.Timestamptz, compilerVersion pgtype.Text, schemaVersion pgtype.Text, validationHash pgtype.Text, createdBy pgtype.Text, updatedBy pgtype.Text) (*Ruleset, error)
}

var _ Querier = (*Queries)(nil)
